import type { Metadata } from "next";
import "./globals.css";
import { ProdutoStateProvider } from "./context/ProdutoStateContext";
import { ProdutoContextProvider } from "./context/ProdutoContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-gray-100">
        <div className="container mx-auto text-gray-500 box-border">
          <ProdutoStateProvider>
            <ProdutoContextProvider>{children}</ProdutoContextProvider>
          </ProdutoStateProvider>
        </div>
      </body>
    </html>
  );
}
